# Generated by Django 3.0.2 on 2020-02-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=50)),
                ('bot_id', models.IntegerField()),
                ('bot_image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
