# Generated by Django 3.0.2 on 2020-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0003_bot_info_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_info',
            name='bot_url',
            field=models.URLField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
