# Generated by Django 3.0.2 on 2020-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0004_bot_info_bot_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_info',
            name='bot_image',
            field=models.ImageField(upload_to='BotImage'),
        ),
    ]
