# Generated by Django 3.0.4 on 2020-03-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0005_auto_20200310_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_info',
            name='bot_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
