# Generated by Django 3.0.4 on 2020-03-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0006_auto_20200313_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='profile_pic',
            field=models.FileField(default='none', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot_info',
            name='bot_image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
