# Generated by Django 3.0.4 on 2020-03-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0007_auto_20200316_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='profile_pic',
            field=models.FileField(default='none', upload_to='media/'),
        ),
    ]
