from django.urls import path
from . import views
urlpatterns = [
    path('',views.Homepage),
    path('Login/',views.Login),
    path('Homepage/',views.Homepage),
    path('Home/',views.Home),
    path('tutorial/',views.tutorial),
    # path('log/',views.log),
    # path('Sign_dup/',views.Signup_dup),
    path('Signup/',views.Signup),
    path('Verify/',views.Verify),
    path('signup/',views.Signup_dup),
    path('login/',views.Login_dup),
    path('startsearch/',views.Startsearch),
    path('Resend_otp/',views.Resend_otp),
    path("Forget_pass/",views.Forget_pass),
    path("forget_password/",views.dup_Forget_pass),
    path("Forget_pass_verify/",views.Forget_pass_verify),
    path("New_password/",views.New_password),
    path("Forget_pass_verify_resend/",views.Forget_pass_verify_resend),
    path("Logout/",views.Logout),
    path('AddBot/',views.AddBot),
    # path('show_add_bot/',views.showAddBot),
    # path('ShowBot/',views.ShowBot),
    path('Change_password/',views.Change_password),
    path('change_password/',views.dup_Change_password),
    path('userProfile/',views.userProfile),
    path('profile_pic/',views.profile_pic),
    path('Remove_bot/',views.Remove_bot),   
    path('dup_addBot/',views.dup_addBot),
    path('about/',views.about),
    path('contact/',views.contact),
]
